#!/usr/bin/env python3
"""
Generate recip_rom.v -- 1024-entry reciprocal lookup table ROM.

Input  index [9:0]:   10 fractional bits below the implicit leading 1 of a
                      normalized value. The actual value is (1024+index)/1024,
                      i.e. in [1.0, 2.0).

Output recip_out [19:0]: 0.19 fixed-point reciprocal.
                      recip_out = round(2^19 / (1.0 + index/1024.0))
                      Range: (0.5, 1.0] -> values in (262144, 524288].

Usage:
    python gen_recip_rom.py > recip_rom.v
"""

import math

def gen_recip_table():
    entries = []
    for index in range(1024):
        val = 1.0 + index / 1024.0
        rounded = round((2**19) / val)
        entries.append(rounded)
    return entries

def main():
    entries = gen_recip_table()

    print("// recip_rom.v")
    print("// Reciprocal approximation ROM, 1024 entries.")
    print("//")
    print("// Input:  index [9:0]  -- 10 fractional bits below the implicit leading 1")
    print("//         Represents the mantissa (1024 + index) / 1024, i.e. in [1.0, 2.0)")
    print("//")
    print("// Output: recip_out [19:0] -- 0.19 fixed-point reciprocal")
    print("//         recip_out = round(2^19 / (1 + index/1024))")
    print("//         Range: (0.5, 1.0] i.e. values in (262144, 524288]")
    print("//")
    print(f"// For index=0:    recip_out = {entries[0]}  (1/1.0    = 1.0,   represented as 2^19)")
    print(f"// For index=512:  recip_out = {entries[512]}  (1/1.5   ~= 0.667, represented as ~2/3 * 2^19)")
    print(f"// For index=1023: recip_out = {entries[1023]}  (1/1.999 ~= 0.5003)")
    print("//")
    print("// Generated by: output = round(2^19 / (1.0 + index/1024.0))")
    print()
    print("module recip_rom (")
    print("    input  wire [ 9:0] index,")
    print("    output reg  [19:0] recip_out")
    print(");")
    print("always @(*) begin")
    print("    case (index)")
    for i, v in enumerate(entries):
        print(f"        10'd{i}: recip_out = 20'd{v};")
    print("        default: recip_out = 20'd0;")
    print("    endcase")
    print("end")
    print("endmodule")

if __name__ == "__main__":
    main()
